### PR TITLE
FEAT: Migrate Astra DB Source Connector to the v2 Framework

### PR DESCRIPTION
**Pull request by erichare**
This PR migrates the existing source connector to the v2 framework. Below is some sample code to run a pipeline:

```python
import os

from unstructured_ingest.v2.pipeline.pipeline import Pipeline
from unstructured_ingest.v2.interfaces import ProcessorConfig
from unstructured_ingest.v2.processes.connectors.astradb import (
    AstraDBAccessConfig,
    AstraDBConnectionConfig,
    AstraDBDownloaderConfig,
    AstraDBIndexerConfig,
)
from unstructured_ingest.v2.processes.partitioner import PartitionerConfig
from unstructured_ingest.v2.processes.connectors.local import LocalUploaderConfig

# Chunking and embedding are optional.

if __name__ == "__main__":
    Pipeline.from_configs(
        context=ProcessorConfig(),
        indexer_config=AstraDBIndexerConfig(
            collection_name=os.getenv("ASTRA_DB_COLLECTION"),
            keyspace=os.getenv("ASTRA_DB_KEYSPACE"),           
        ),
        downloader_config=AstraDBDownloaderConfig(
            collection_name=os.getenv("ASTRA_DB_COLLECTION"),
            keyspace=os.getenv("ASTRA_DB_KEYSPACE"),
        ),
        source_connection_config=AstraDBConnectionConfig(
            access_config=AstraDBAccessConfig(
                token=os.getenv("ASTRA_DB_APPLICATION_TOKEN"),
                api_endpoint=os.getenv("ASTRA_DB_API_ENDPOINT"),
            ),
        ),
        partitioner_config=PartitionerConfig(
            partition_by_api=True,
            partition_endpoint=os.getenv("UNSTRUCTURED_API_URL"),
            api_key=os.getenv("UNSTRUCTURED_API_KEY"),
        ),
        uploader_config=LocalUploaderConfig(output_dir=os.getenv("LOCAL_FILE_OUTPUT_DIR")),
    ).run()
```

### CODE REVIEW

**Comment by erichare** [comment]
@potter-potter the docs were clear enough that this was pretty quick :) Let me know if there's any issues

**Comment by potter-potter** [comment]
@erichare thanks for doing this! Will take a bit to get to look at this. We are pushing to get something launched early next week so that's our focus.

**Comment by erichare** [comment]
Totally understand! Thanks David!On Sep 27, 2024, at 5:45 PM, David Potter ***@***.***> wrote:﻿
@erichare thanks for doing this! Will take a bit to get to look at this. We are pushing to get something launched early next week so that's our focus.

**Comment by potter-potter** [comment]
@erichare this works great! I'll take it over and put it into a new branch so that we have an easier time with CI/CD

**Comment by erichare** [comment]
Awesome! @potter-potter . As i was working on it, i realized there's a lot of open questions about some pieces of it (does it make sense that we take a full Astra DB row / record and convert it to a text file with key, value pairs? seems a little like we're taking structured data, making it "unstructured", then converting back haha which might be a little silly - at the same time, it opens up some possibilities for converting legacy collections / tables to a more modern framework with more sensible chunking + enabling embeddings... and this is how the v1 source connector was operating anyway... so i figured those questions can be deferred, for now. It's a niche usecase in all likelihood but better to have the functionality than not.

Sounds great about the Ci/CD. Thank you! let me know if there's anything to address.

**Comment by potter-potter** [comment]
> Awesome! @potter-potter . As i was working on it, i realized there's a lot of open questions about some pieces of it (does it make sense that we take a full Astra DB row / record and convert it to a text file with key, value pairs? seems a little like we're taking structured data, making it "unstructured", then converting back haha which might be a little silly - at the same time, it opens up some possibilities for converting legacy collections / tables to a more modern framework with more sensible chunking + enabling embeddings... and this is how the v1 source connector was operating anyway... so i figured those questions can be deferred, for now. It's a niche usecase in all likelihood but better to have the functionality than not.
> 
> Sounds great about the Ci/CD. Thank you! let me know if there's anything to address.

I hear you about the converting to txt file and back. Thats our current procedure. I think we'll revisit soon when we have better visibility on folks using table style source connectors.

**Comment by erichare** [comment]
@potter-potter Just checking if it's safe to close this in favor of the PR you have open? Thanks!

**Pull request closed without merging**
