### PR TITLE
feat/validate read/write permissions in fsspec prechecks

### PR DESCRIPTION
**Pull request by rbiseck3**
### Description
Check write access for fsspec destination connectors by writing a small blank file to the desired location. 

This was checked with a properly configured access run and without and got the expected error when access was permitted: 
```
unstructured_ingest.error.DestinationConnectionError: failed to validate connection: Access Denied
```

The indexer was also updated to make a head request on the first file it listed to check read permissions.

### CODE REVIEW

**Comment by ryannikolaidis** [comment]
add a test that fails with no write access and succeeds with access?

**Review by six5532one — COMMENTED** [review]
I see that `precheck` is defined for `FsspecUploader` and `FsspecIndexer`. Would it make sense to also define `precheck` for `FsspecDownloader`, since `get` is a distinct functionality?

**Comment by rbiseck3** [comment]
@six5532one the issue with having a precheck for the downloader is we would need a sample file to read to validate the connection. But there's no guarantee that's there's a really file in the destination we can use for the downloader and the downloader doesn't know what files exist there until the indexer runs.

**Review by ryannikolaidis — APPROVED** [review]
lgtm!

**Pull request merged**
