### PR TITLE
bugfix: rebrand from Astra to Astra DB

### PR DESCRIPTION
**Pull request by erichare**
This pull request provides a corresponding renaming from `Astra` (and `astra`) to `AstraDB` (and astradb) where appropriate. See here for more details:

https://github.com/Unstructured-IO/unstructured/pull/3458

### CODE REVIEW

**Comment by erichare** [comment]
CC @potter-potter , hopefully didn't miss anywhere! :)

**Comment by rbiseck3** [comment]
If this can be rebased, then we can move ahead with merging it in.

**Comment by erichare** [comment]
@rbiseck3 just made my attempt at rebasing it. Hope i didn't mess anything up 😄

**Comment by erichare** [comment]
@rbiseck3 can you tell failing workflow is something related to this PR? It didn’t look like it at first glance to me, but I may have missed something

**Comment by rbiseck3** [comment]
Will merge for now, given that all other CI tests passed.

**Review by rbiseck3 — APPROVED** [review]

**Comment by rbiseck3** [comment]
Merged this in for now given all other CI tests passed.

**Pull request merged**
