### PR TITLE
FIX: use find instead of paginated_find in source connector

### PR DESCRIPTION
**Pull request by erichare**
This PR fixes the Astra DB source connector to be compatible with AstraPy 1.5.0+

### CODE REVIEW

**Comment by erichare** [comment]
@awalker4 @potter-potter sorry about the issue here! This should fix the problem with the paginated_find() method.

**Comment by erichare** [comment]
@awalker4 Just checking, would you like me to bump the version to 0.0.21 and add a changelog entry to fix the linting issue here?

**Comment by potter-potter** [comment]
@erichare looks like this fix is in the old astradb.py I'll see if it fixes CI and will also try it in v2.

I know its confusing but only v2 versions run unless we haven't converted them over yet. Soon all connectors will be converted. Astradb was converted to v2 a while ago.
https://github.com/Unstructured-IO/unstructured-ingest/blob/main/unstructured_ingest/v2/processes/connectors/astradb.py

**Comment by potter-potter** [comment]
Though this does seem to fix the astrapy test. Thanks!

**Comment by erichare** [comment]
> Though this does seem to fix the astrapy test. Thanks!

Glad to hear it, and sorry about the build issue. I should have caught that one!

**Comment by potter-potter** [comment]
@erichare my mistake. I think we are using astradb.py in v1 for a source connector still.

**Comment by erichare** [comment]
> @erichare my mistake. I think we are using astradb.py in v1 for a source connector still.

I think you are correct. I was looking this morning at migrating it to a v2 source connector - i dont know if there's an "easy" way to do that, or a guide, but i'd be happy to if you'd like.

**Comment by potter-potter** [comment]
@erichare The V2 docs are here:
https://github.com/Unstructured-IO/unstructured/blob/129abd0a14c51194824c3b7f7fad9623b7cbfa54/unstructured/ingest/v2/README2.md
But they might need an overhaul.

**Comment by awalker4** [comment]
Some of the ingest test output has changed - I ran the update ingest tests action on my branch the other day. So, let me go ahead and merge that as 0.0.21-dev0 and that should get the tests sorted over here.

**Comment by awalker4** [comment]
> @awalker4 Just checking, would you like me to bump the version to 0.0.21 and add a changelog entry to fix the linting issue here?

I think that makes sense!

**Comment by erichare** [comment]
@potter-potter you've incorporated this fix into your branch, right? So my question from above may not apply. Let me know if i should just close this.

**Comment by potter-potter** [comment]
@erichare you can close this. The same thing is in my branch.

**Pull request closed without merging**
